services:
  postgres:
    image: postgres:15
    container_name: forkito-postgres
    environment:
      POSTGRES_DB: forkito_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
